sudo: required
services:
    - docker

before_install:
    - docker build -t biplabchakraborty/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true biplabchakraborty/docker-react npm run test 