sudo: required
services:
    - docker

before_install:
    - docker build -t biplabchakraborty/docker-react -f Dockerfile.dev .

script:
    - docker run biplabchakraborty/docker-react npm run test -- --coverage